### ISSUE TITLE
aqi service fails in case sensor meassure very high amount of particles

### ISSUE THREAD

**Issue by xslima00** [jonathankoren/weewx-aqi#36]
```
Aug 19 19:10:19 new-weather-machine journal: weewx[26377] INFO weewx.manager: Added record 2022-08-19 19:09:34 CEST (1660928974) to database 'purpleair.sdb'
Aug 19 19:10:19 new-weather-machine journal: weewx[26377] INFO weewx.manager: Added record 2022-08-19 19:09:34 CEST (1660928974) to daily summary in 'purpleair.sdb'
Aug 19 19:10:19 new-weather-machine journal: weewx[26377] INFO weewx.engine: Main loop exiting. Shutting engine down.
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] INFO user.interceptor: shutting down server thread
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__: Caught unrecoverable exception:
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  AQI can not be calculated from this table
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  Traceback (most recent call last):
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 214, in run
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.CHECK_LOOP, packet=packet))
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      callback(event)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 634, in check_loop
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      raise BreakLoop
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  weewx.engine.BreakLoop
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  Traceback (most recent call last):
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 650, in post_loop
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      self._catchup(self.engine.console.genArchiveRecords)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 697, in _catchup
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      for record in generator(lastgood_ts):
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/__init__.py", line 30, in genArchiveRecords
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      raise NotImplementedError("Method 'genArchiveRecords' not implemented")
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  NotImplementedError: Method 'genArchiveRecords' not implemented
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  Traceback (most recent call last):
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 153, in main
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      engine.run()
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 221, in run
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.POST_LOOP))
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      callback(event)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 652, in post_loop
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      self._software_catchup()
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 717, in _software_catchup
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      origin='software'))
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      callback(event)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/service.py", line 342, in new_archive_record
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      self.aqi_standard.calculate_aqi(pollutant, required_unit, joined)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/standards.py", line 57, in calculate_aqi
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      return self.calculators[pollutant].calculate(pollutant, observation_unit, observations)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/calculators.py", line 182, in calculate
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      return self._calculate_index_from_mean(obs_mean)
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/calculators.py", line 282, in _calculate_index_from_mean
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****      raise IndexError('AQI can not be calculated from this table')
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  IndexError: AQI can not be calculated from this table
Aug 19 19:10:20 new-weather-machine journal: weewx[26377] CRITICAL __main__:     ****  Exiting.

```

**Comment by xslima00** [comment]
OK, I see this issue was already reported here

https://github.com/jonathankoren/weewx-aqi/issues/35
