### ISSUE TITLE
WeeWX crashing

### ISSUE THREAD

**Issue by misko903** [jonathankoren/weewx-aqi#39]
Hello,
could you help me with the issue - weewx-aqi crashing the weewx?

```
Dec 28 09:46:54 WeeWX weewx[28536] WARNING weewx.qc: 2022-12-28 09:46:00 CET (1672217160) Archive value 'extraTemp1' 196.088 outside limi                                                    ts (-40.0, 120.0)
Dec 28 09:46:54 WeeWX weewx[28536] WARNING weewx.qc: 2022-12-28 09:46:00 CET (1672217160) Archive value 'pm10_0' -0.5 outside limits (0.0                                                    , 500.0)
Dec 28 09:46:54 WeeWX weewx[28536] WARNING weewx.qc: 2022-12-28 09:46:00 CET (1672217160) Archive value 'pm2_5' 98966.41 outside limits (                                                    0.0, 500.0)
Dec 28 09:46:54 WeeWX weewx[28536] INFO weewx.engine: Main loop exiting. Shutting engine down.
Dec 28 09:46:54 WeeWX weewx[28536] INFO user.interceptor: shutting down server thread
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__: Caught unrecoverable exception:
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  list index out of range
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  Traceback (most recent call last):
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 214, in run
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.CHECK_LOOP, packet=packet))
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      callback(event)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 634, in check_loop
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      raise BreakLoop
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  weewx.engine.BreakLoop
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  Traceback (most recent call last):
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 650, in post_loop
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      self._catchup(self.engine.console.genArchiveRecords)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 697, in _catchup
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      for record in generator(lastgood_ts):
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/__init__.py", line 30, in genArchi                                                    veRecords
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      raise NotImplementedError("Method 'genArchiveRecords' not implemented                                                    ")
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  NotImplementedError: Method 'genArchiveRecords' not implemented
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  Traceback (most recent call last):
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      engine.run()
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 221, in run
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.POST_LOOP))
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      callback(event)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 652, in post_loop
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      self._software_catchup()
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 715, in _software_catchup
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      self.engine.dispatchEvent(weewx.Event(weewx.NEW_ARCHIVE_RECORD,
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      callback(event)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/service.py", line 355, in new_archive_r                                                    ecord
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      self.aqi_standard.calculate_aqi(pollutant, required_unit, joined)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/standards.py", line 57, in calculate_aq                                                    i
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      return self.calculators[pollutant].calculate(pollutant, observation_u                                                    nit, observations)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/calculators.py", line 172, in calculate
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      last_valid_index = get_last_valid_index(observations, self.duration_i                                                    n_secs)
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****    File "/usr/share/weewx/user/aqi/calculators.py", line 38, in get_last_v                                                    alid_index
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****      first_invalid_timestamp = observations[0][0] - duration_in_secs
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  IndexError: list index out of range
Dec 28 09:46:54 WeeWX weewx[28536] CRITICAL __main__:     ****  Exiting.
```
I have the latest Master branch installed.
thank you,
Michal

**Comment by jonathankoren** [comment]
I suspect that you don’t have any observations.

—
jonathan koren
***@***.***
http://www.jonathankoren.com

**Comment by jonathankoren** [comment]
Try the latest v1.4.1 release

**Comment by misko903** [comment]
Hi,
thanks for the update, I have loaded the 1.4.1, however, my AQI feinstaub sensor is now already working, therefore I can't test it.
Thanks,
Michal
